[workspace]

resolver = "2"

members = [
    "core",
    "gui",
]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "deny"
nursery = "deny"
all = "deny"

# Clippy rant go brrrrr...
missing_const_for_fn = "allow"