[workspace]

resolver = "2"

members = ["core"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "deny"
nursery = "deny"

# A collection of Clippy lints that do more harm than good.
missing_const_for_fn = "allow"
new_without_default = "allow"
