[package]
name = "milton_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
milton_core = { path = "../core" }
iced = "0.10.0"

[lints]
workspace = true
